[package]
name = "vault-read"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-frontmatter = { workspace = true }
hypr-fs-format = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
specta = { workspace = true, features = ["derive", "serde_json"] }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = { workspace = true }
