// This file has been generated by Specta. DO NOT EDIT.

export type NativeImportResult = { path: string; durationSeconds: number; title?: string }

export type NativeModelStatus = { ready: boolean; downloading: boolean; modelId: string; revision: string; downloadedBytes: number; totalBytes: number; phase: string }

export type NativeVaultSelection = { path: string | null }

export type NativeWord = { text: string; start: number; end: number }
